Retire rpi2 bb jetson
Picovoice/porcupine pull request #1295
Opened 2024-08-14 22:42 UTC by albho

2024-08-19 19:01 UTC, laves requested changes

2024-08-22 19:30 UTC, albho commented on README.md
> +#### Linux (x86_64), macOS (x86_64), and Raspberry Pi
Omitted RPI 2 for all since it was removed too

2024-08-26 22:10 UTC, laves approved these changes

2024-08-26 22:11 UTC, laves commented
do you have to release some packages before the merge?

2024-08-26 22:16 UTC, albho commented
> do you have to release some packages before the merge?

@laves yes, I'll re-push changes after releasing and let you know when it's good to merge

2024-08-27 17:53 UTC, merged