Node binding v2.0
Picovoice/porcupine pull request #518
Opened 2021-11-04 20:23 UTC by laves

2021-11-06 00:37 UTC, mrrostam approved these changes

2021-11-07 02:41 UTC, kenarsa requested changes

2021-11-07 02:41 UTC, kenarsa commented on binding/nodejs/README.md
> +- Windows (x86_64)
Jetson and Beaglebone

2021-11-07 02:41 UTC, kenarsa commented on binding/nodejs/index.js
> +    if(!accessKey || accessKey.length === 0) {
`accessKey === null || accessKey === undefined || accessKey.length === 0`

2021-11-07 02:41 UTC, kenarsa commented on demo/nodejs/README.md
>  - Raspberry Pi (2,3,4)
Jetson and Beaglebone

2021-11-08 17:56 UTC, merged