Github actions nodejs add machines and non-English tests
Picovoice/porcupine pull request #598
Opened 2021-12-21 01:42 UTC by iliadrm

2021-12-21 21:25 UTC, ksyeo1010 commented on binding/nodejs/index.test.js
> +    let counts = porcupineDetectionCounts(
for the `porcupineDetectionCounts`, we should do the same as in python with paths:

```javascript
const path = require("path")

let some_path = path.join(__dirname, "path_relative_to_this_directory")
```

2021-12-21 22:37 UTC, ksyeo1010 approved these changes

2021-12-23 22:01 UTC, laves requested changes

2021-12-23 22:01 UTC, laves commented on binding/nodejs/index.test.js
> +  test("multiple keyword multiple detection", () => {
```suggestion
  test("multiple keyword multiple detection in FR", () => {
```

2021-12-23 22:01 UTC, laves commented on binding/nodejs/index.test.js
> +  test("multiple keyword multiple detection", () => {
```suggestion
  test("multiple keyword multiple detection in ES", () => {
```

2021-12-23 22:01 UTC, laves commented on binding/nodejs/index.test.js
> +  test("multiple keyword multiple detection", () => {
```suggestion
  test("multiple keyword multiple detection in DE", () => {
```

2021-12-23 23:14 UTC, laves requested changes

2021-12-23 23:14 UTC, laves commented on binding/nodejs/index.test.js
>  const SENSITIVITIES_1 = [0.5];
can you just rename this like `DEFAULT_SENSITIVITY_ARRAY` or something? since we're not going to create anymore.

2021-12-23 23:50 UTC, merged