Github actions go add platforms and non-English tests
Picovoice/porcupine pull request #605
Opened 2021-12-28 18:17 UTC by iliadrm

2021-12-28 18:51 UTC, kenarsa commented on binding/go/porcupine_test.go
> +	pvTestAccessKey string
I know this is not part of this code change but I rather drop the `pv` here. You can use something like `testAccessKey` or even `accessKey`.

2021-12-28 18:51 UTC, kenarsa commented on binding/go/porcupine_test.go
> +	p               Porcupine
in the previous version, `p` was local in a function and it made sense to have a short name for it. Now that it has a larger scope we prob should give it a better name. `porcupine` ...

2021-12-28 18:51 UTC, kenarsa commented on binding/go/porcupine_test.go
> +	modelPath, _ := filepath.Abs(fmt.Sprintf(
with nested calls that don't fit into a line please prefer to break them like below:

```go
relPath = fmt.Sprintf(
		"../../lib/common/%s.pv",
		appendLanguage("porcupine_params", language))
filepath.Abs(relPath)
```

2021-12-28 18:51 UTC, kenarsa commented on binding/go/porcupine_test.go
> +	testFile, _ := filepath.Abs(filepath.Join("../../resources/audio_samples", audioFileName))
`testAudioPath` ?

2021-12-28 19:23 UTC, kenarsa approved these changes

2021-12-28 21:45 UTC, laves requested changes
I'm liking this pattern we've settled on for the new tests!

2021-12-28 21:45 UTC, laves commented on binding/go/porcupine_test.go
> +	testAduioPath, _ := filepath.Abs(filepath.Join("../../resources/audio_samples", audioFileName))
```suggestion
	testAudioPath, _ := filepath.Abs(filepath.Join("../../resources/audio_samples", audioFileName))
```

2021-12-28 21:45 UTC, laves commented
Can you look into why Beaglebone failed?

2021-12-29 02:12 UTC, laves approved these changes

2021-12-29 02:12 UTC, merged