Vue
Picovoice/porcupine pull request #771
Opened 2022-08-25 18:24 UTC by ksyeo1010

- add vue interface

2022-08-25 19:52 UTC, laves requested changes

2022-08-25 19:52 UTC, laves commented on binding/vue/src/porcupine.ts
> +  pause: () => Promise<void>,
Just need to remove `pause` and add `release` here to match the interface we settled on

2022-08-25 20:59 UTC, laves approved these changes

2022-08-25 21:02 UTC, ErisMik approved these changes

2022-08-25 21:15 UTC, mrrostam approved these changes

2022-08-26 01:14 UTC, ksyeo1010 commented
- Implemented interface. Had to do callbacks since variables are not updated. 
- updated demo to Vue3 (still works in vue 2, rhino/picovoice can still be Vue 2).

2022-08-26 16:42 UTC, ErisMik commented on binding/vue/README.md
> +
Is this necessary to mention since we already include a way to get the errors through the sdk?

2022-08-26 16:42 UTC, ErisMik commented on binding/vue/README.md
> +After done with Porcupine, either call `release` or destroy the mounted component:
```suggestion
When done with Porcupine, either call `release` or destroy the mounted component:
```

2022-08-26 16:50 UTC, ErisMik commented on demo/vue/src/components/VoiceWidget.vue
> +    <button v-on:click="stop" :disabled="!isLoaded || error || !isListening">
I've been including "release" here too to kinda reset the demo, not sure if that's something we want to do though? I don't have any strong opinions

2022-08-26 17:58 UTC, ErisMik approved these changes

2022-08-30 17:13 UTC, laves requested changes

2022-08-30 17:38 UTC, ksyeo1010 commented on README.md
> +yarn add @picovoice/porcupine-vue @picovoice/web-voice-processor
yes, its a peer-dep so we should. the binding itself is broken if they dont install it.

2022-08-30 17:42 UTC, ksyeo1010 commented on binding/vue/README.md
> +yarn add @picovoice/porcupine-vue @picovoice/web-voice-processor
yes

2022-08-30 21:41 UTC, laves approved these changes

2022-08-31 22:36 UTC, merged